package cc.mrbird.febs.timetable.entity;

public enum TimetableAddState {
    SAMECLASSSAMETIMECLASH,
    SAMETEACHERSAMETIMECLASH,
    CLASSROOMPEOPLEAMOUNTCLASH,
    SAMECLASSROOMSAMETIMECLASH,
    COURSEPERIODCLASH,
    SUCCESS
}
